# Imagem inicial
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Definindo diretório dentro do container
WORKDIR C:/app

# Copiando os executáveis para o container
COPY TrabalhoComparavel/output/Sequencial.exe .
COPY TrabalhoComparavel/output/MultiThread.exe .
COPY TrabalhoComparavel/output/MultiProcess.exe .

CMD ["cmd", "/S", "/C", "Sequencial.exe && MultiThread.exe 4 && MultiProcess.exe 4"]
